### PR TITLE
Add support for additional security groups.

### PR DESCRIPTION
**Pull request by alistair**
This pull requests does what it says on the tin :)

FYI api documentation is located here
http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_Ec2InstanceAttributes.html

### CODE REVIEW

**Comment by robert2d** [comment]
This is perfect! I am OoO today but will merge tomorrow morning

**Comment by alistair** [comment]
sweet thanks.   loving the project btw

**Comment by alistair** [comment]
@robert2d ping.  and chance we could get this merged?  Thanks

**Comment by robert2d** [comment]
Sorry mate, just haven't merged cause I needed to do a release. :watch: I'm going to do it right now :smile:

**Comment by robert2d** [comment]
Okay 6.0.8 has been released. Thanks a lot for the additional feature!

**Pull request merged**
