### PR TITLE
Spark step

### PR DESCRIPTION
**Pull request by BenFradet**

### CODE REVIEW

**Comment by BenFradet** [comment]
On a side note, I think it'd be great to inspect the steps in the job flow and add the appropriate applications.

For example, if there are a Spark and a S3DistCp steps, add the Hadoop and Spark applications.

**Comment by BenFradet** [comment]
Hey @robert2d , do you see anything else that needs to be added/reviewed to get this merged?

**Comment by robert2d** [comment]
Sorry @BenFradet I totally missed this in my inbox. I'll setup a release ASAP

**Comment by BenFradet** [comment]
Thanks a bunch! :+1:

**Comment by robert2d** [comment]
Both pull requests are now in master and released in version 6.0.11

**Comment by BenFradet** [comment]
Great, thanks a lot!

**Pull request merged**
