### PR TITLE
added security configuration attribute

### PR DESCRIPTION
**Pull request by devsaik**
Essential attribute for most of the corporate AWS Environments

### CODE REVIEW

**Comment by rslifka** [comment]
Thank you for the PR! Would you please add a spec for this (see /spec for examples) and resubmit?

**Comment by devsaik** [comment]
@rslifka, Hopefully this spec should help.

**Comment by devsaik** [comment]
@rslifka: Is there anything I should correct in my PR ?

**Comment by rslifka** [comment]
@robert2d ☝️ , Sorry I shouldn't have jumped in 😄

**Comment by robert2d** [comment]
I've been subscribed to too many repos lately and have missed notifications 😞

**Pull request merged**
