### PR TITLE
AMI 4.x support

### PR DESCRIPTION
**Pull request by robert2d**
- [x] additional info added
- [x] S3DistCp defaults to new JAR location for AMI >= 4.x

### CODE REVIEW

**Comment by robert2d** [comment]
Hey @fblundun, I made a couple of changes to your code and added a few specs for the new features. but your commits are still in there ;)

**Comment by fblundun** [comment]
Thanks for the release @robert2d , it's working well!

One more question: for AMI 3.x, we had to do some additional Hadoop configuration for a particular input format. [This](https://github.com/snowplow/snowplow/blob/2001aef473215d3422b5a9ae61537b1c4b94465e/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_job.rb#L107-L112) is how we did it, using Elasticity's HadoopBootstrapAction.

But in 4.x, [predefined bootstrap actions are replaced by configurations](http://docs.aws.amazon.com/ElasticMapReduce/latest/ReleaseGuide/emr-release-differences.html#release-differences-bootstrap). It looks like we should start using the new `Elasticity::Application` class. Do you have any idea how to translate our old bootstrap logic into an Application configuration?

Many thanks!

**Comment by fblundun** [comment]
Update: I didn't see a way to set configurations in the Elasticity API so I ended up putting them directly into the payload by monkey patching the AwsRequestV4 class [here](https://github.com/snowplow/snowplow/blob/r77-rebase/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/emr_job.rb#L28-L49).

**Comment by robert2d** [comment]
Yea looks like a new "feature" that needs to added. I'll create an issue for now

**Comment by robert2d** [comment]
On the subject of Applications you can see them in the readme now [here](http://docs.aws.amazon.com/ElasticMapReduce/latest/ReleaseGuide/emr-release-differences.html#release-differences-bootstrap)

**Pull request merged**
