### PR TITLE
Make script steps work in any region

### PR DESCRIPTION
**Pull request by BenFradet**
Same issue as in #135

### CODE REVIEW

**Comment by BenFradet** [comment]
ping @robert2d in case you missed it :+1: (there is also #135)

**Comment by robert2d** [comment]
I could be wrong, but having a first look at this it would be a breaking change for existing implementations of this GEM. Would it not be beneficial to use the `config.region` setter method and utilise it within the script step instead?

**Comment by BenFradet** [comment]
>I could be wrong, but having a first look at this it would be a breaking change for existing implementations of this GEM.

True, didn't pay attention to this aspect.

>Would it not be beneficial to use the config.region setter method and utilise it within the script step instead?

I'm having trouble seeing how I could access the region from within the script step.
Or are you suggesting replacing the script step by a custom jar step on our side in which case we could change the region at will?

**Comment by BenFradet** [comment]
ping @robert2d in case you forgot about this :+1:

**Comment by alexanderdean** [comment]
@BenFradet - can you make this a non-breaking change? Maybe with an additional `initialize` option? I think that would make it much easier for @robert2d to merge...

**Comment by BenFradet** [comment]
@robert2d 

We're going to circumvent this by going the `CustomJarStep` route for now. Do you want me to leave this open for a future version introducing breaking changes or should I close it?

Also, could you have a look at #138 and #140 ? Thanks.

**Pull request closed without merging**
