### PR TITLE
Add Custom tagging

### PR DESCRIPTION
**Pull request by kmcrawford**

### CODE REVIEW

**Comment by rslifka** [comment]
Awesome, thanks!

A couple of questions:

- How are multiple tags specified?
- Are there illegal characters or delimiters that Elasticity should know about?  Really just making sure that no matter what you put in for a tag value, that the command can be submitted so that EMR can provide an error message.

Please go ahead and create the associated specs, which would also serve to answer these questions as the tests themselves are a form of documentation.

**Comment by kmcrawford** [comment]
- :tags - (Array<) A list of tags to associate with a cluster and
   propagate to Amazon EC2 instances.
      - :key - (String) A user-defined key, which is the minimum required
      information for a valid tag.
      - :value - (String) A user-defined value, which is optional in a tag.


Example:

@myEMRJob.tags = [
       {:name => "my tag name 1", :value => "my tag value 1"},
       {:name => "my tag name 2", :value => "my tag value 2"},
]

Ken Crawford


Architect, Global eCommerce | Office Depot, Inc.
6600 N Military Tr | Boca Raton, FL 33496
Tel: 561.438.5196 | ken.crawford@officedepot.com

CONFIDENTIALITY NOTICE: The information contained in this email and
attached document(s) may contain confidential information that is intended
only for the addressee(s). If you are not the intended recipient, you are
hereby advised that any disclosure, copying, distribution or the taking of
any action in reliance upon the information is prohibited. If you have
received this email in error, please immediately notify the sender and
delete it from your system.

**Comment by rslifka** [comment]
Awesome, thanks Ken.  I think in that case an API like this would be preferred.

```
@jobflow.add_tag("tag name 1", "tag value 1")
```

...otherwise it's not clear how you should be using this method.

Also, if you could add the tests under `/spec`, that would be great, thanks!

**Comment by kmcrawford** [comment]
Rob,
I'm not a ruby developer so I'm not sure how to implement what you are requesting.  

According to the documentation below you can use a add_tags api but it still expects and array and the resource_id (which I'm not sure where to find).

So to do what I think you are requesting you would have to add_tag locally then when done apply the tags using the tags passing the array as I did before.  This is where my ruby skills are limited to do this correctly.

http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/EMR/Client.html#add_tags-instance_method

**Comment by rslifka** [comment]
Gotcha, thanks @kmcrawford!  I'll use your PR as a starting point to complete the implementation.

**Comment by rslifka** [comment]
Folding in to 6.0.

**Pull request closed without merging**
