### PR TITLE
New EMR features (Applications | Release Label)

### PR DESCRIPTION
**Pull request by robert2d**
## Add New EMR features
This pull request aims to incorporate the [latest EMR changes](http://docs.aws.amazon.com/ElasticMapReduce/latest/ReleaseGuide/emr-release-differences.html) but still allow older applications to use this library with an upgrade. This will allow people using any of the supported applications (hadoop, hive, pig and spark) see [here](https://aws.amazon.com/blogs/aws/elastic-mapreduce-release-4-0-0-with-updated-applications-now-available/) for blog post on latest updates by Jeff.

### Changes
- [x] added `Application` class to handle adding emr [applications](http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_Application.html)
- [x] release_label attribute added.
- [x] prevented adding ami_version and release_label
- [x] prevented adding applications without adding release_label

### Important notes
* ami_version is now set in config preamble and will default to latest when release label isn't set
* release label is a swap out for ami version for EMR > 4.0* but it does not default to anything

### AWS EMR release notes
See the [Release Notes](http://docs.aws.amazon.com/ElasticMapReduce/latest/ReleaseGuide/emr-release-differences.html) for the changes I have included in this pull request

### CODE REVIEW

**Comment by robert2d** [comment]
Links to https://github.com/rslifka/elasticity/issues/85

**Comment by rslifka** [comment]
Awesome @robert2d!  Going to do a release?

**Comment by robert2d** [comment]
Yea I just wanted to wait till after RE:Invent to see if they were going to change things even further but this is pretty much good to go. I spiking a Spark job this week so will incorporate this branch into it just to do some final testing etc..

**Comment by robert2d** [comment]
Before this goes in it needs the readme updated. I have begun work on a new EMR project and will be merging this in next week after updating the documentation and trying this branch out as a ad hoc integration test. links too: https://github.com/rslifka/elasticity/issues/121

**Pull request merged**
