### PR TITLE
Make application configuration available

### PR DESCRIPTION
**Pull request by henryhu666**
In EMR, we can override default configurations for installed applications by supplying a configuration json file: e.g http://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-configure-apps.html.
Adding this attribute in elasticity to allow users to add configurations in hash forms.

### CODE REVIEW

**Comment by BenFradet** [comment]
@robert2d any updates on this?

**Comment by henryhu666** [comment]
I updated the PR because I assume the configurations are given in Json hash forms (e.g. { "key": "value" } ) as in EMR doc. Hence, it is not necessary to `convert_ruby_to_aws_v4` for configurations.

**Comment by robert2d** [comment]
Thanks @henryhu666. Sorry for taking so long @BenFradet been on paternity leave. Back into action today will have a release out momentarily.

**Comment by BenFradet** [comment]
No problem 👍 , glad you're back.

**Pull request merged**
