### PR TITLE
AMI 4.x support

### PR DESCRIPTION
**Pull request by fblundun**
This PR was created by rebasing https://github.com/rslifka/elasticity/pull/120 onto the master branch, then adding support for the additonal_info field and making the S3DistCpStep work for both the old and the new AMIs.

### CODE REVIEW

**Comment by fblundun** [comment]
Copying in @alexanderdean and @robert2d

**Comment by fblundun** [comment]
Hey @rslifka , any chance this could be merged soon? Our next release depends on support for the latest AMI series.

**Comment by robert2d** [comment]
Hey mate, I'll make sure I do this tomorrow morning. Been meaning to get to it for ages now. Just need to fix up these tests and update the README. Shouldn't take long.

**Comment by fblundun** [comment]
Thanks @robert2d !

**Comment by robert2d** [comment]
Going to merge #120 first and run the tests again on this pull request afterward. Then I'll release it into the wild

**Comment by robert2d** [comment]
Okay so I have merged the EMR 4.0.0 upgrades. Could I ask you too please rebase/merge origin/master and then push again, it should fix Travis for you as well. Otherwise there is a new version containing 4.0.0 updates. But I'd rather not just copy your S3DistCp work without your attribution :smile:

**Comment by fblundun** [comment]
Thanks @robert2d , I've rebased now!

**Comment by robert2d** [comment]
Nice give me till Monday and I'll merge that in!

--
Dave Robertson
CricHQ
E: david.robertson@crichq.com
Ph: ‭+61 437 648 516‬

On 29/01/2016, at 8:38 PM, Fred Blundun <notifications@github.com> wrote:

Thanks @robert2d <https://github.com/robert2d> , I've rebased now!

—
Reply to this email directly or view it on GitHub
<https://github.com/rslifka/elasticity/pull/123#issuecomment-176665106>.

**Comment by robert2d** [comment]
closing in favour of #125

**Pull request closed without merging**
